# Generated by Django 2.2.2 on 2019-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default='', help_text='Enter a brief description of your life', max_length=1000),
        ),
    ]
