# Generated by Django 2.2.2 on 2019-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogger_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Enter a comment here', max_length=500),
        ),
    ]
